package ru.moscow.foxkiss.auction;

import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.java.JavaPlugin;
import ru.moscow.foxkiss.database.H2LibraryLoader;
import ru.moscow.foxkiss.gui.AuctionViewType;
import ru.moscow.foxkiss.utils.TextUtils;

import javax.sql.DataSource;
import java.nio.file.Path;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;

public final class H2AuctionRepository implements AuctionRepository {
    private static final int active = 0;
    private static final int processing = 1;

    private final JavaPlugin plugin;
    private final String jdbcUrl;
    private DataSource dataSource;

    public H2AuctionRepository(JavaPlugin plugin) {
        this.plugin = plugin;
        Path dbPath = plugin.getDataFolder().toPath().resolve("auction").toAbsolutePath();
        this.jdbcUrl = "jdbc:h2:file:" + dbPath + ";MODE=MySQL";
    }

    @Override
    public void init() {
        plugin.getDataFolder().mkdirs();
        dataSource = H2LibraryLoader.loadDataSource(plugin, jdbcUrl);

        try (Connection conn = open(); Statement st = conn.createStatement()) {
            st.executeUpdate("""
                CREATE TABLE IF NOT EXISTS auction_items(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    seller_name TEXT NOT NULL,
                    currency TEXT NOT NULL,
                    item TEXT NOT NULL,
                    price REAL NOT NULL,
                    created_at BIGINT NOT NULL,
                    status INTEGER DEFAULT 0,
                    material TEXT,
                    amount INTEGER DEFAULT 1,
                    price_per_item REAL
                )
                """);

            st.executeUpdate("""
                CREATE TABLE IF NOT EXISTS sales_history(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    seller_name TEXT NOT NULL,
                    buyer_name TEXT NOT NULL,
                    currency TEXT NOT NULL,
                    item_type TEXT NOT NULL,
                    amount INTEGER NOT NULL,
                    price REAL NOT NULL,
                    sold_at BIGINT NOT NULL
                )
                """);

            ensureColumns(conn);
            migrateAmounts(conn);
            migratePricePerItem(conn);

            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_auction_currency_status ON auction_items(currency,status)");
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_auction_currency_status_created ON auction_items(currency,status,created_at)");
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_auction_currency_status_price ON auction_items(currency,status,price)");
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_auction_currency_status_price_per_item ON auction_items(currency,status,price_per_item)");
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_auction_seller_currency_status ON auction_items(seller_name,currency,status)");
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_auction_material_currency_status ON auction_items(material,currency,status)");
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_sales_currency_time ON sales_history(currency,sold_at)");
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_sales_seller ON sales_history(seller_name,currency)");

        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Ошибка инициализации БД", e);
        }
    }

    private void ensureColumns(Connection conn) throws SQLException {
        DatabaseMetaData meta = conn.getMetaData();
        try (ResultSet rs = meta.getColumns(null, null, "AUCTION_ITEMS", "CREATED_AT")) {
            if (!rs.next() || rs.getInt("DATA_TYPE") != Types.BIGINT) {
                try (Statement st = conn.createStatement()) {
                    st.executeUpdate("ALTER TABLE auction_items ALTER COLUMN created_at BIGINT");
                }
            }
        }
        try (ResultSet rs = meta.getColumns(null, null, "AUCTION_ITEMS", "AMOUNT")) {
            if (!rs.next()) {
                try (Statement st = conn.createStatement()) {
                    st.executeUpdate("ALTER TABLE auction_items ADD COLUMN amount INTEGER DEFAULT 1");
                }
            }
        }
        try (ResultSet rs = meta.getColumns(null, null, "AUCTION_ITEMS", "PRICE_PER_ITEM")) {
            if (!rs.next()) {
                try (Statement st = conn.createStatement()) {
                    st.executeUpdate("ALTER TABLE auction_items ADD COLUMN price_per_item REAL");
                }
            }
        }
    }

    private void migrateAmounts(Connection conn) {
        try (PreparedStatement select = conn.prepareStatement("SELECT id,item,amount FROM auction_items WHERE amount IS NULL OR amount<=0");
             PreparedStatement update = conn.prepareStatement("UPDATE auction_items SET amount=? WHERE id=?");
             ResultSet rs = select.executeQuery()) {
            while (rs.next()) {
                try {
                    ItemStack item = deserialize(rs.getString("item"));
                    update.setInt(1, Math.max(1, item.getAmount()));
                    update.setLong(2, rs.getLong("id"));
                    update.addBatch();
                } catch (Exception ignored) {}
            }
            update.executeBatch();
        } catch (SQLException ignored) {}
    }

    private void migratePricePerItem(Connection conn) {
        try (PreparedStatement select = conn.prepareStatement("SELECT id,price,amount FROM auction_items WHERE price_per_item IS NULL");
             PreparedStatement update = conn.prepareStatement("UPDATE auction_items SET price_per_item=? WHERE id=?");
             ResultSet rs = select.executeQuery()) {
            while (rs.next()) {
                double price = rs.getDouble("price");
                int amount = rs.getInt("amount");
                double pricePerItem = (amount > 0) ? price / amount : price;
                update.setDouble(1, pricePerItem);
                update.setLong(2, rs.getLong("id"));
                update.addBatch();
            }
            update.executeBatch();
        } catch (SQLException ignored) {}
    }

    @Override
    public long create(String sellerName, AuctionCurrency currency, ItemStack itemStack, double price) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO auction_items(seller_name,currency,item,price,created_at,status,material,amount,price_per_item) " + "VALUES(?,?,?,?,?,?,?,?,?)", Statement.RETURN_GENERATED_KEYS)) {

            int amount = itemStack.getAmount();
            double pricePerItem = (amount > 0) ? price / amount : price;

            ps.setString(1, sellerName);
            ps.setString(2, currency.name());
            ps.setString(3, serialize(itemStack));
            ps.setDouble(4, price);
            ps.setLong(5, System.currentTimeMillis());
            ps.setInt(6, active);
            ps.setString(7, itemStack.getType().name());
            ps.setInt(8, amount);
            ps.setDouble(9, pricePerItem);
            ps.executeUpdate();

            try (ResultSet keys = ps.getGeneratedKeys()) {
                return keys.next() ? keys.getLong(1) : -1L;
            }
        } catch (Exception e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка создания лота", e);
            return -1L;
        }
    }

    @Override
    public List<AuctionItem> findPage(AuctionCurrency currency, int page, int pageSize, AuctionSort sort, String category, String sellerFilter, String searchFilter) {
        try (Connection conn = open()) {
            return findPageWithConnection(conn, currency, page, pageSize, sort, category,
                    sellerFilter, searchFilter, AuctionViewType.MAIN, -1L, null);
        } catch (SQLException e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка поиска страницы", e);
            return List.of();
        }
    }

    @Override
    public MenuData loadMenuData(AuctionCurrency currency, String playerName, int maxDays, int page, int pageSize, AuctionSort sort, String category, String sellerFilter, String searchFilter, AuctionViewType viewType) {
        long cutoff = System.currentTimeMillis() - maxDays * 86_400_000L;
        try (Connection conn = open()) {
            List<AuctionItem> items = findPageWithConnection(conn, currency, page, pageSize, sort, category, sellerFilter, searchFilter, viewType, cutoff, playerName);
            int totalCount = countTotal(conn, currency, viewType, category, sellerFilter, searchFilter, playerName, cutoff);

            int sellingCount = 0, expiredCount = 0;
            if (viewType == AuctionViewType.MAIN) {
                try (PreparedStatement ps = conn.prepareStatement(
                        "SELECT COUNT(CASE WHEN status=? THEN 1 END) as selling, " + "COUNT(CASE WHEN status=? AND created_at<? THEN 1 END) as expired " + "FROM auction_items WHERE currency=? AND seller_name=?")) {
                    ps.setInt(1, active);
                    ps.setInt(2, active);
                    ps.setLong(3, cutoff);
                    ps.setString(4, currency.name());
                    ps.setString(5, playerName);
                    try (ResultSet rs = ps.executeQuery()) {
                        if (rs.next()) {
                            sellingCount = rs.getInt("selling");
                            expiredCount = rs.getInt("expired");
                        }
                    }
                }
            }
            return new MenuData(items, totalCount, sellingCount, expiredCount);
        } catch (SQLException e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка загрузки меню", e);
            return new MenuData(List.of(), 0, 0, 0);
        }
    }

    private int countTotal(Connection conn, AuctionCurrency currency, AuctionViewType viewType, String category, String sellerFilter, String searchFilter, String playerName, long cutoff) throws SQLException {
        List<Object> params = new ArrayList<>();
        params.add(currency.name());
        params.add(active);
        StringBuilder sql = new StringBuilder("SELECT COUNT(*) FROM auction_items WHERE currency=? AND status=?");

        if (viewType == AuctionViewType.MAIN) {
            if (TextUtils.isNotBlank(category) && !category.equalsIgnoreCase("all")) {
                sql.append(" AND material=?");
                params.add(category.toUpperCase(Locale.ROOT));
            }
            if (TextUtils.isNotBlank(sellerFilter)) {
                sql.append(" AND seller_name LIKE ?");
                params.add("%" + sellerFilter + "%");
            }
            if (TextUtils.isNotBlank(searchFilter)) {
                sql.append(" AND (material LIKE ? OR seller_name LIKE ?)");
                params.add("%" + searchFilter + "%");
                params.add("%" + searchFilter + "%");
            }
        } else if (viewType == AuctionViewType.SELLING) {
            sql.append(" AND seller_name = ?");
            params.add(playerName);
        } else if (viewType == AuctionViewType.EXPIRED) {
            sql.append(" AND seller_name = ?");
            params.add(playerName);
            sql.append(" AND created_at < ?");
            params.add(cutoff);
        }

        try (PreparedStatement ps = conn.prepareStatement(sql.toString())) {
            for (int i = 0; i < params.size(); i++) {
                ps.setObject(i + 1, params.get(i));
            }
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getInt(1) : 0;
            }
        }
    }

    private List<AuctionItem> findPageWithConnection(Connection conn, AuctionCurrency currency, int page, int pageSize, AuctionSort sort, String category, String sellerFilter, String searchFilter, AuctionViewType viewType, long cutoff, String playerName) throws SQLException {
        List<Object> params = new ArrayList<>();
        params.add(currency.name());
        params.add(active);
        StringBuilder sql = new StringBuilder("SELECT * FROM auction_items WHERE currency=? AND status=?");

        if (viewType == AuctionViewType.MAIN) {
            if (TextUtils.isNotBlank(category) && !category.equalsIgnoreCase("all")) {
                sql.append(" AND material=?");
                params.add(category.toUpperCase(Locale.ROOT));
            }
            if (TextUtils.isNotBlank(sellerFilter)) {
                sql.append(" AND seller_name LIKE ?");
                params.add("%" + sellerFilter + "%");
            }
            if (TextUtils.isNotBlank(searchFilter)) {
                sql.append(" AND (material LIKE ? OR seller_name LIKE ?)");
                params.add("%" + searchFilter + "%");
                params.add("%" + searchFilter + "%");
            }
        } else if (viewType == AuctionViewType.SELLING) {
            sql.append(" AND seller_name = ?");
            params.add(playerName);
        } else if (viewType == AuctionViewType.EXPIRED) {
            sql.append(" AND seller_name = ?");
            params.add(playerName);
            sql.append(" AND created_at < ?");
            params.add(cutoff);
        }

        String orderBy = switch (sort) {
            case NEWEST -> "created_at DESC";
            case OLDEST -> "created_at ASC";
            case EXPENSIVE -> "price DESC";
            case CHEAP -> "price ASC";
            case EXPENSIVE_PER_ITEM -> "price_per_item DESC, id DESC";
            case CHEAP_PER_ITEM -> "price_per_item ASC, id ASC";
        };
        sql.append(" ORDER BY ").append(orderBy);
        sql.append(" LIMIT ? OFFSET ?");
        int safePage = Math.max(0, page);
        int safePageSize = Math.max(1, pageSize);
        params.add(safePageSize);
        params.add(safePage * safePageSize);

        List<AuctionItem> items = new ArrayList<>();
        try (PreparedStatement ps = conn.prepareStatement(sql.toString())) {
            for (int i = 0; i < params.size(); i++) {
                ps.setObject(i + 1, params.get(i));
            }
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    items.add(readItem(rs));
                }
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
        return items;
    }

    @Override
    public Optional<AuctionItem> findById(long id) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement("SELECT * FROM auction_items WHERE id=?")) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? Optional.of(readItem(rs)) : Optional.empty();
            }
        } catch (Exception e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка поиска лота по ID", e);
            return Optional.empty();
        }
    }

    @Override
    public boolean delete(long id) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement("DELETE FROM auction_items WHERE id=?")) {
            ps.setLong(1, id);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка удаления лота", e);
            return false;
        }
    }

    @Override
    public void recordSale(String sellerName, String buyerName, AuctionCurrency currency,
                           String itemType, int amount, double price) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO sales_history(seller_name,buyer_name,currency,item_type,amount,price,sold_at) VALUES(?,?,?,?,?,?,?)")) {
            ps.setString(1, sellerName);
            ps.setString(2, buyerName);
            ps.setString(3, currency.name());
            ps.setString(4, itemType);
            ps.setInt(5, amount);
            ps.setDouble(6, price);
            ps.setLong(7, System.currentTimeMillis());
            ps.executeUpdate();
        } catch (SQLException e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка записи продажи", e);
        }
    }

    @Override
    public boolean markAsSelling(long id) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement("UPDATE auction_items SET status=? WHERE id=? AND status=?")) {
            ps.setInt(1, processing);
            ps.setLong(2, id);
            ps.setInt(3, active);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка пометки лота как продающегося", e);
            return false;
        }
    }

    @Override
    public void restoreStatus(long id) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement("UPDATE auction_items SET status=? WHERE id=? AND status=?")) {
            ps.setInt(1, active);
            ps.setLong(2, id);
            ps.setInt(3, processing);
            ps.executeUpdate();
        } catch (SQLException e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка восстановления статуса лота", e);
        }
    }

    @Override
    public List<TopSeller> getTopSellers(AuctionCurrency currency, int limit) {
        List<TopSeller> sellers = new ArrayList<>();
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement("SELECT seller_name, COUNT(*) AS sold, COALESCE(SUM(price),0) AS earned " + "FROM sales_history WHERE currency=? GROUP BY seller_name ORDER BY sold DESC LIMIT ?")) {
            ps.setString(1, currency.name());
            ps.setInt(2, limit);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    sellers.add(new TopSeller(rs.getString("seller_name"), rs.getInt("sold"), rs.getDouble("earned")));
                }
            }
        } catch (SQLException e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка получения топ-продавцов", e);
        }
        return sellers;
    }

    @Override
    public PlayerStats getPlayerStats(String playerName, AuctionCurrency currency) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement("SELECT COUNT(*) AS sold, COALESCE(SUM(price),0) AS earned " + "FROM sales_history WHERE seller_name=? AND currency=?")) {
            ps.setString(1, playerName);
            ps.setString(2, currency.name());
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return new PlayerStats(rs.getInt("sold"), rs.getDouble("earned"));
                }
            }
        } catch (SQLException e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка получения статистики игрока", e);
        }
        return new PlayerStats(0, 0);
    }

    @Override
    public List<String> getUniqueMaterialNames(AuctionCurrency currency) {
        List<String> names = new ArrayList<>();
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement("SELECT DISTINCT material FROM auction_items WHERE currency=? AND status=? AND material IS NOT NULL")) {
            ps.setString(1, currency.name());
            ps.setInt(2, active);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    names.add(rs.getString("material"));
                }
            }
        } catch (SQLException e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка получения уникальных материалов", e);
        }
        return names;
    }

    @Override
    public int countActiveBySellerSince(String sellerName, AuctionCurrency currency, long since) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT COUNT(*) FROM auction_items WHERE seller_name=? AND currency=? AND created_at>? AND status=?")) {
            ps.setString(1, sellerName);
            ps.setString(2, currency.name());
            ps.setLong(3, since);
            ps.setInt(4, active);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getInt(1) : 0;
            }
        } catch (SQLException e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка подсчёта активных лотов продавца", e);
            return 0;
        }
    }

    @Override
    public void close() {
        if (dataSource == null) return;
        try {
            dataSource.getClass().getMethod("dispose").invoke(dataSource);
        } catch (ReflectiveOperationException e) {
            plugin.getLogger().log(Level.WARNING, "Ошибка закрытия пула подключений", e);
        }
    }

    private AuctionItem readItem(ResultSet rs) throws Exception {
        ItemStack item = deserialize(rs.getString("item"));
        int amount = rs.getInt("amount");
        if (amount > 0) {
            item.setAmount(amount);
        }
        return new AuctionItem(
                rs.getLong("id"),
                rs.getString("seller_name"),
                AuctionCurrency.valueOf(rs.getString("currency")),
                item,
                rs.getDouble("price"),
                rs.getLong("created_at"),
                AuctionStatus.fromInt(rs.getInt("status"))
        );
    }

    private Connection open() throws SQLException {
        if (dataSource == null) {
            throw new SQLException("DataSource не инициализирован");
        }
        return dataSource.getConnection();
    }

    private String serialize(ItemStack item) throws Exception {
        return Base64.getEncoder().encodeToString(item.serializeAsBytes());
    }

    private ItemStack deserialize(String data) throws Exception {
        return ItemStack.deserializeBytes(Base64.getDecoder().decode(data));
    }
}