package ru.moscow.foxkiss.auction;

import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.java.JavaPlugin;
import ru.moscow.foxkiss.database.H2LibraryLoader;

import javax.sql.DataSource;
import java.nio.file.Path;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;

public final class H2AuctionRepository implements AuctionRepository {

    private static final int activeStatus = 0;
    private static final int proccesStart = 1;

    private final JavaPlugin plugin;
    private final String jdbcUrl;
    private DataSource dataSource;

    public H2AuctionRepository(JavaPlugin plugin) {
        this.plugin = plugin;
        Path dbPath = plugin.getDataFolder().toPath().resolve("auction").toAbsolutePath();
        this.jdbcUrl = "jdbc:h2:file:" + dbPath + ";MODE=MySQL";
    }

    @Override
    public void init() {
        plugin.getDataFolder().mkdirs();
        dataSource = H2LibraryLoader.loadDataSource(plugin, jdbcUrl);

        try (Connection conn = open(); Statement st = conn.createStatement()) {
            st.executeUpdate("""
                CREATE TABLE IF NOT EXISTS auction_items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    seller_name TEXT NOT NULL,
                    currency TEXT NOT NULL,
                    item TEXT NOT NULL,
                    price REAL NOT NULL,
                    created_at BIGINT NOT NULL,
                    status INTEGER DEFAULT 0,
                    material TEXT
                )
                """);
            st.executeUpdate("""
                CREATE TABLE IF NOT EXISTS sales_history (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    seller_name TEXT NOT NULL,
                    buyer_name TEXT NOT NULL,
                    currency TEXT NOT NULL,
                    item_type TEXT NOT NULL,
                    amount INTEGER NOT NULL,
                    price REAL NOT NULL,
                    sold_at BIGINT NOT NULL
                )
                """);
            migrateCreatedAtColumn(conn, st);
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_sales_currency_time ON sales_history(currency, sold_at)");
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_sales_seller ON sales_history(seller_name, currency)");

        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Failed to initialize database", e);
        }
    }

    private void migrateCreatedAtColumn(Connection connection, Statement statement) throws SQLException {
        try (ResultSet columns = connection.getMetaData().getColumns(null, null, "AUCTION_ITEMS", "CREATED_AT")) {
            if (columns.next() && columns.getInt("DATA_TYPE") == Types.BIGINT) {
                return;
            }
        }
        statement.executeUpdate("ALTER TABLE auction_items ALTER COLUMN created_at BIGINT");
    }

    @Override
    public long create(String sellerName, AuctionCurrency currency, ItemStack itemStack, double price) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO auction_items(seller_name,currency,item,price,created_at,status,material) VALUES(?,?,?,?,?,?,?)",
                     Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, sellerName);
            ps.setString(2, currency.name());
            ps.setString(3, serialize(itemStack));
            ps.setDouble(4, price);
            ps.setLong(5, System.currentTimeMillis());
            ps.setInt(6, activeStatus);
            ps.setString(7, itemStack.getType().name());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                return keys.next() ? keys.getLong(1) : -1L;
            }
        } catch (Exception e) {
            plugin.getLogger().log(Level.SEVERE, "Create auction failed", e);
            return -1L;
        }
    }

    @Override
    public List<AuctionItem> findPage(AuctionCurrency currency, int page, int pageSize,
                                      AuctionSort sort, String category, String sellerFilter, String searchFilter) {
        List<AuctionItem> items = new ArrayList<>();
        
        List<Object> params = new ArrayList<>();
        params.add(currency.name());
        params.add(activeStatus);

        StringBuilder sql = new StringBuilder();
        sql.append("SELECT * FROM auction_items WHERE currency = ? AND status = ?");

        if (category != null && !category.isEmpty() && !"all".equalsIgnoreCase(category)) {
            sql.append(" AND material = ?");
            params.add(category.toUpperCase());
        }
        if (sellerFilter != null && !sellerFilter.isEmpty()) {
            sql.append(" AND seller_name LIKE ?");
            params.add("%" + sellerFilter + "%");
        }
        if (searchFilter != null && !searchFilter.isEmpty()) {
            sql.append(" AND (material LIKE ? OR seller_name LIKE ?)");
            params.add("%" + searchFilter + "%");
            params.add("%" + searchFilter + "%");
        }

        String orderBy = switch (sort) {
            case NEWEST -> "created_at DESC";
            case OLDEST -> "created_at ASC";
            case EXPENSIVE -> "price DESC";
            case CHEAP -> "price ASC";
            case EXPENSIVE_PER_ITEM -> "price / item.amount DESC";
            case CHEAP_PER_ITEM -> "price / item.amount ASC";
        };
        sql.append(" ORDER BY ").append(orderBy);
        sql.append(" LIMIT ? OFFSET ?");
        
        int offset = page * pageSize;
        params.add(pageSize);
        params.add(offset);

        String finalSql = sql.toString();

        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(finalSql)) {
            for (int i = 0; i < params.size(); i++) {
                ps.setObject(i + 1, params.get(i));
            }
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    items.add(readItem(rs));
                }
            }
        } catch (Exception e) {
            plugin.getLogger().log(Level.SEVERE, "Find page failed", e);
        }
        return items;
    }

    @Override
    public int countAll(AuctionCurrency currency, String category, String sellerFilter, String searchFilter) {
        StringBuilder sql = new StringBuilder("SELECT COUNT(*) FROM auction_items WHERE currency=? AND status=?");
        
        List<Object> params = new ArrayList<>();
        params.add(currency.name());
        params.add(activeStatus);

        if (category != null && !category.isEmpty() && !"all".equalsIgnoreCase(category)) {
            sql.append(" AND material=?");
            params.add(category.toUpperCase());
        }
        if (sellerFilter != null && !sellerFilter.isEmpty()) {
            sql.append(" AND seller_name LIKE ?");
            params.add("%" + sellerFilter + "%");
        }
        if (searchFilter != null && !searchFilter.isEmpty()) {
            sql.append(" AND (material LIKE ? OR seller_name LIKE ?)");
            params.add("%" + searchFilter + "%");
            params.add("%" + searchFilter + "%");
        }

        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(sql.toString())) {
            for (int i = 0; i < params.size(); i++) {
                ps.setObject(i + 1, params.get(i));
            }
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt(1);
                }
            }
        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Count all failed", e);
        }
        return 0;
    }

    @Override
    public int countSellingByPlayer(AuctionCurrency currency, String playerName) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT COUNT(*) FROM auction_items WHERE currency=? AND seller_name=? AND status=?")) {
            ps.setString(1, currency.name());
            ps.setString(2, playerName);
            ps.setInt(3, activeStatus);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return rs.getInt(1);
            }
        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Count selling by player failed", e);
        }
        return 0;
    }

    @Override
    public int countExpiredByPlayer(AuctionCurrency currency, String playerName, int maxDays) {
        long cutoff = System.currentTimeMillis() - maxDays * 86_400_000L;
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT COUNT(*) FROM auction_items WHERE currency=? AND seller_name=? AND created_at < ? AND status=?")) {
            ps.setString(1, currency.name());
            ps.setString(2, playerName);
            ps.setLong(3, cutoff);
            ps.setInt(4, activeStatus);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return rs.getInt(1);
            }
        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Count expired by player failed", e);
        }
        return 0;
    }

    @Override
    public Optional<AuctionItem> findById(long id) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement("SELECT * FROM auction_items WHERE id=?")) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? Optional.of(readItem(rs)) : Optional.empty();
            }
        } catch (Exception e) {
            plugin.getLogger().log(Level.SEVERE, "Find by id failed", e);
            return Optional.empty();
        }
    }

    @Override
    public boolean delete(long id) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement("DELETE FROM auction_items WHERE id=?")) {
            ps.setLong(1, id);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Delete failed", e);
            return false;
        }
    }

    @Override
    public void recordSale(String sellerName, String buyerName, AuctionCurrency currency, String itemType, int amount, double price) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO sales_history(seller_name,buyer_name,currency,item_type,amount,price,sold_at) VALUES(?,?,?,?,?,?,?)")) {
            ps.setString(1, sellerName);
            ps.setString(2, buyerName);
            ps.setString(3, currency.name());
            ps.setString(4, itemType);
            ps.setInt(5, amount);
            ps.setDouble(6, price);
            ps.setLong(7, System.currentTimeMillis());
            ps.executeUpdate();
        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Record sale failed", e);
        }
    }

    @Override
    public boolean markAsSelling(long id) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(
                     "UPDATE auction_items SET status=? WHERE id=? AND status=?")) {
            ps.setInt(1, proccesStart);
            ps.setLong(2, id);
            ps.setInt(3, activeStatus);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Mark as selling failed", e);
            return false;
        }
    }

    @Override
    public void restoreStatus(long id) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(
                     "UPDATE auction_items SET status=? WHERE id=? AND status=?")) {
            ps.setInt(1, activeStatus);
            ps.setLong(2, id);
            ps.setInt(3, proccesStart);
            ps.executeUpdate();
        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Restore status failed", e);
        }
    }

    @Override
    public List<TopSeller> getTopSellers(AuctionCurrency currency, int limit) {
        List<TopSeller> sellers = new ArrayList<>();
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT seller_name, COUNT(*) as sold, COALESCE(SUM(price), 0) as earned " +
                             "FROM sales_history WHERE currency=? GROUP BY seller_name ORDER BY sold DESC LIMIT ?")) {
            ps.setString(1, currency.name());
            ps.setInt(2, limit);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    sellers.add(new TopSeller(
                            rs.getString("seller_name"),
                            rs.getInt("sold"),
                            rs.getDouble("earned")
                    ));
                }
            }
        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Get top sellers failed", e);
        }
        return sellers;
    }

    @Override
    public PlayerStats getPlayerStats(String playerName, AuctionCurrency currency) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT COUNT(*) as sold, COALESCE(SUM(price), 0) as earned " +
                             "FROM sales_history WHERE seller_name=? AND currency=?")) {
            ps.setString(1, playerName);
            ps.setString(2, currency.name());
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return new PlayerStats(rs.getInt("sold"), rs.getDouble("earned"));
                }
                return new PlayerStats(0, 0.0);
            }
        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Get player stats failed", e);
            return new PlayerStats(0, 0.0);
        }
    }

    @Override
    public List<String> getUniqueMaterialNames(AuctionCurrency currency) {
        List<String> names = new ArrayList<>();
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT DISTINCT material FROM auction_items WHERE currency=? AND status=? AND material IS NOT NULL")) {
            ps.setString(1, currency.name());
            ps.setInt(2, activeStatus);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    names.add(rs.getString("material"));
                }
            }
        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Get unique materials failed", e);
        }
        return names;
    }

    @Override
    public int countActiveBySellerSince(String sellerName, AuctionCurrency currency, long since) {
        try (Connection conn = open();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT COUNT(*) FROM auction_items WHERE seller_name=? AND currency=? AND created_at>? AND status=?")) {
            ps.setString(1, sellerName);
            ps.setString(2, currency.name());
            ps.setLong(3, since);
            ps.setInt(4, activeStatus);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt(1);
                }
            }
        } catch (SQLException e) {
            plugin.getLogger().log(Level.SEVERE, "Count active by seller since failed", e);
        }
        return 0;
    }

    @Override
    public void close() {
        if (dataSource == null) return;
        try {
            dataSource.getClass().getMethod("dispose").invoke(dataSource);
        } catch (ReflectiveOperationException exception) {
            plugin.getLogger().log(Level.WARNING, "Failed to close H2 connection pool", exception);
        }
    }

    private AuctionItem readItem(ResultSet rs) throws Exception {
        return new AuctionItem(
                rs.getLong("id"),
                rs.getString("seller_name"),
                AuctionCurrency.valueOf(rs.getString("currency")),
                deserialize(rs.getString("item")),
                rs.getDouble("price"),
                rs.getLong("created_at"),
                AuctionStatus.fromInt(rs.getInt("status"))
        );
    }

    private Connection open() throws SQLException {
        if (dataSource == null) throw new SQLException("H2 connection pool is not initialized");
        return dataSource.getConnection();
    }

    private String serialize(ItemStack itemStack) throws Exception {
        return Base64.getEncoder().encodeToString(itemStack.serializeAsBytes());
    }

    private ItemStack deserialize(String data) throws Exception {
        return ItemStack.deserializeBytes(Base64.getDecoder().decode(data));
    }
}